swagger: "2.0"

info:
  description: |-
    Pi-Hole Local DNS / DHCP management external API

    This project provides an API to manage some of the DHCP/DNS resources on a pi-hole server:

      - Static DHCP entries
      - Local DNS entries
      - CNAME aliases


        Some useful links:
    - [Pi-Hole Manager repository](https://github.com/gringolito/pi-hole-manager)
  version: "0.1.0"
  title: "Pi-Hole Manager"
  contact:
    email: "filipeutzig@gmail.com"
  license:
    name: "Beerware"
    url: "https://raw.githubusercontent.com/gringolito/pi-hole-manager/master/LICENSE"

host: "localhost"
basePath: "/api/v1"

tags:
- name: "Static hosts"
  description: "Manage static DHCP entries"

schemes:
- "http"

paths:
  /static/hosts:
    get:
      tags:
      - "Static hosts"
      summary: "Get all the static DHCP hosts"
      description: "Return the list of all static DHCP entries on the pi-hole server"
      operationId: "GetAllStaticHosts"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/DHCPHost"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []

  /static/host:
    get:
      tags:
      - "Static hosts"
      summary: "Get a static DHCP host by MAC/IP address"
      description: "Returns a DHCP host entry"
      operationId: "GetStaticHost"
      produces:
      - "application/json"
      parameters:
      - name: "mac"
        in: "query"
        description: "MAC address of the host"
        required: false
        type: "string"
        format: "mac"
      - name: "ip"
        in: "query"
        description: "IP address of the host"
        required: false
        type: "string"
        format: "ipv4"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DHCPHost"
        "400":
          description: "Invalid query supplied"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: "Host not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []

    post:
      tags:
      - "Static hosts"
      summary: "Add a new static DHCP host"
      description: "Create a new static DHCP host entry if the host doesn't exists"
      operationId: "AddStaticHost"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "DHCP host object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/DHCPHost"
      responses:
        "201":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DHCPHost"
        "400":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []

    put:
      tags:
      - "Static hosts"
      summary: "Add or update a static DHCP host"
      description: "Add or update a static DHCP host entry"
      operationId: "UpdateStaticHost"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "DHCP host object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/DHCPHost"
      responses:
        "201":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DHCPHost"
        "400":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []

    delete:
      tags:
      - "Static hosts"
      summary: "Delete a static DHCP host by MAC/IP address"
      description: "Remove a DHCP host entry"
      operationId: "RemoveStaticHost"
      produces:
      - "application/json"
      parameters:
      - name: "mac"
        in: "query"
        description: "MAC address of the host"
        required: false
        type: "string"
        format: "mac"
      - name: "ip"
        in: "query"
        description: "IP address of the host"
        required: false
        type: "string"
        format: "ipv4"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DHCPHost"
        "204":
          description: "Nothing to be done"
        "400":
          description: "Invalid query supplied"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: "Host not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []


securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  DHCPHost:
    type: "object"
    required:
    - "MacAddress"
    - "IPAddress"
    - "HostName"
    properties:
      MacAddress:
        type: "string"
        format: "mac"
        example: "00:11:22:33:44:55"
      IPAddress:
        type: "string"
        format: "ipv4"
        example: "10.0.0.1"
      HostName:
        type: "string"
        format: "hostname"
        example: "foo.bar"

  ErrorResponse:
    type: "object"
    properties:
      error:
        type: "string"
        example: "something went wrong"
